#!/bin/bash
BASEDIR="$(dirname "$BASH_SOURCE")"
cd "$BASEDIR"

if [ $EUID -ne 0 ]; then
    echo -e "\n*********This script must be run with root priviledge*********"
    echo -e "*******************Sorry! Exiting*************************\n"
    exit 1
fi

jdkgenre="jdk"
jdkver="$1"
[[ $jdkver == "" ]] && 
{
#jdkver=$(java -version 2>&1|grep -ioP "(?<=^java\sversion\s[\"'])[^\"]*")  # -P flag is not portable
jdkver=$(java -version 2>&1 |sed -n "s/^java[[:blank:]]*version[[:blank:]]*[\"']\([^\"']*\)[\"'].*/\1/pI")
read -e -i "$jdkver" -p "Enter the jdk version: " jdkver
}
jdkname=$jdkgenre$jdkver
[[ -d /usr/lib/jvm/$jdkname ]] || 
{ 
printf "%s\n" "-----Directory not found: /usr/lib/jvm/$jdkname-----
"; exit 2;
}


[[ $jdkname == "" || $jdkname =~ \/ ]] && echo "------jdkname can not be empty or contain /------" && exit 3


for prog in /usr/lib/jvm/$jdkname/bin/*;do
    progn="${prog##*/}"
    [[ $progn == *"."* ]] && continue
    if [[ -f $prog ]];then
        update-alternatives --remove "$progn" "/usr/lib/jvm/$jdkname/bin/$progn"
    fi
done

rm -rf "/usr/lib/jvm/$jdkname" && echo "
***removed: /usr/lib/jvm/$jdkname***"

h1="export J2SDKDIR=/usr/lib/jvm/$jdkname"
h2="export J2REDIR=/usr/lib/jvm/$jdkname/jre"
h3="export PATH=\$PATH:/usr/lib/jvm/$jdkname/bin:/usr/lib/jvm/$jdkname/db/bin:/usr/lib/jvm/$jdkname/jre/bin"
h4="export JAVA_HOME=/usr/lib/jvm/$jdkname"
h5="export DERBY_HOME=/usr/lib/jvm/$jdkname/db"

pat1="$(echo "$h1" |sed 's/[^^]/[&]/g; s/\^/\\^/g')"
pat2="$(echo "$h2" |sed 's/[^^]/[&]/g; s/\^/\\^/g')"
pat3="$(echo "$h3" |sed 's/[^^]/[&]/g; s/\^/\\^/g')"
pat4="$(echo "$h4" |sed 's/[^^]/[&]/g; s/\^/\\^/g')"
pat5="$(echo "$h5" |sed 's/[^^]/[&]/g; s/\^/\\^/g')"

sed --in-place "/^$pat1/d" /etc/profile &&
sed --in-place "/^$pat2/d" /etc/profile &&
sed --in-place "/^$pat3/d" /etc/profile &&
sed --in-place "/^$pat4/d" /etc/profile &&
sed --in-place "/^$pat5/d" /etc/profile &&
source /etc/profile >/dev/null &&
echo "
***removed environment variables***"

rm ~/.mozilla/plugins/libnpjp2.so && echo >/dev/null 2>&1 "
***Mozilla plugin removed***" ||
echo "---Mozilla plugin not found (ignore this error)---" # optional

echo "
******Uninstall Finished******"

